# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  (81..84).each do |i|

    #定义节点变量
    config.vm.define "hadoop#{i}" do |hadoop|

      # box配置
      hadoop.vm.box = "centos/7"
      # 设置虚拟机的主机名
      hadoop.vm.hostname = "hadoop#{i}"
      # 设置虚拟机要使用的宿主机网卡名称
      hadoop.vm.network "public_network", ip: "192.168.8.#{i}", bridge: [
        "wlp3s0",
        "enp4s0f1",
        "ens33",
      ]

      hadoop.vm.allow_hosts_modification = true
      hadoop.vm.box_check_update = false
      hadoop.disksize.size = "100GB"

      hadoop.vm.provision "shell", inline: <<-SHELL
        # disable selinux
        setenforce 0
        sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config

        # https://teamsmiley.github.io/2018/03/17/vagrant-ssh-root/
        # root password set
        sudo -s;
        echo -e "123456\n123456" | passwd;
        # root login allow
        sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config;
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config;
        systemctl restart sshd;

        yum install -y https://repo.ius.io/ius-release-el7.rpm \
        https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
        wget net-tools htop tcping vim;
        ifconfig;
      SHELL

      # VirtaulBox相关配置
      hadoop.vm.provider "virtualbox" do |v|
        v.gui = false
        # 设置虚拟机的名称
        v.name = "hadoop#{i}"

        # 设置虚拟机的内存大小
        v.memory = 4096

        # 设置虚拟机的CPU个数
        v.cpus = 2
      end
    end
  end
end
